/// Flutter icons Background_Icons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Background_Icons
///      fonts:
///       - asset: fonts/Background_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Background_Icons {
  Background_Icons._();

  static const _kFontFam = 'Background_Icons';
  static const String? _kFontPkg = null;

  static const IconData mic = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
