/// Flutter icons Progress_Icons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Progress_Icons
///      fonts:
///       - asset: fonts/Progress_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Progress_Icons {
  Progress_Icons._();

  static const _kFontFam = 'Progress_Icons';
  static const String? _kFontPkg = null;

  static const IconData one_fill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_fill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
